### ISSUE TITLE
Creating default context

### ISSUE THREAD

**Issue by pedrodbsa** [pardahlman/RawRabbit#128]
I'm trying to set up a service that receives messages from non-RR origins (separate Node services). These messages, however, do not ship with the required attributes (headers and body properties) that are used to extract the context, if I understood correctly.

In these cases, I would like to add a default Context (AdvancedMessageContext) to the messages received since I want to use the retry feature.

Extending the current MessageContextProvider won't work because the methods called for the extraction are closed. I could of course re-implement a completely new MessageContextProvider based on yours but I was wondering if there is a cleaner way of doing it or if you are planning on adding this functionality.

I'm happy to contribute.

**Comment by pardahlman** [comment]
`RawRabbit` is designed to work well with other clients, [as long as they communicate with deserializable json bodies](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/SimpleUse/PublishAndSubscribeTests.cs#L309). 

If the received message does not contain any message context, all context related code will bail out at an early stage. While I think this is the right approach for the default implementation, it does not work out well in your scenario. We should make sure to make to mark appropriate functions as `virtual` in the `MessageContextPrividerBase` , so that you can override the default behavior. A PR to `stable` would be much appreciated! 

The workaround until then would be to implement your custom `IMessageContextProvider` (as you suggest).

Hope this helps!
