### ISSUE TITLE
Community feedback

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/RawRabbit#168]
Do you have any suggestions, feedback or ideas for RawRabbit 2.0? Any pain points with high level (.NET) RabbitMq clients you uses today?

**Comment by cocowalla** [comment]
I'd like to have some control over the level of concurrency, either built-in or through an extension point.

RawRabbit 1.x always trys to process consume messages 'as soon as possible', but there are times when you want to throttle/control things a bit.

**Comment by jcasale** [comment]
Possibly prefetch makes more sense (and this facility already exists), that's probably more synonymous with a distributed pattern anyway.

**Comment by pardahlman** [comment]
@cocowalla thanks for your input!

Can you elaborate a bit more on the scenario(s) where you find that feature useful?
Would you like to throttle based on message type, queue or by total number of messages processed in the client? Is the number of concurrent un-acked messages the issue, or is it the concurrency itself?

Thanks!

**Comment by cocowalla** [comment]
I'd like options for both coarse control by setting a 'global' maximum, and fine control by throttling by message type. Ideally there should also be an extension point so that users can define their own concurrency strategy - for example, I might want to group different message types together and specify limits for each group.

The issue is the concurrency itself; for example, let#s say processing a message is IO intensive, and you want your application to not use all available resources.

**Comment by pardahlman** [comment]
Rightio, it as been asked before and should be fairly simple to implement. Issue #169 is created

**Comment by dlaptin-softheme** [comment]
There is a typo here:
http://rawrabbit.readthedocs.io/en/master/Getting-started.html

Search for the word 'registed'.

And 'Edit on GitHub' link is broken.

What is the right way to point you to a typo or to fix it?
Thanks
