### ISSUE TITLE
Unable to remove task completition source for Publish Confirm 

### ISSUE THREAD

**Issue by PeterKottas** [pardahlman/RawRabbit#180]
Hi, I am pretty sure that this is more my not understanding exactly how this works than an issue, but let's give it a shot anyways. 

I am doing some PublishAsync among other things and I noticed these lines come up everytime I publish. Now the lvl is Warn, so I am not that worried, but still would be great to understand. Can you tell me why I see these for every publish? Am I missing some config? 

[08:41:39] [$8] [INFO] [PublishAcknowledger]: Recieved ack for 1540/3 with multiple set to 'False'
[08:41:39] [$8] [DEBUG] [PublishAcknowledger]: Unable to get ack timer for 1540/3.
[08:41:39] [$8] [WARN] [PublishAcknowledger]: Unable to remove task completion source for Publish Confirm on '1540/3'.

Thanks

**Comment by pardahlman** [comment]
Hello @PeterKottas - thanks for reporting this!

This was a mystery to myself for quite some time, but I think I understand what's going on. The reason you're seeing this is because the client counter in RawRabbit is off-sync with the broker counter in RabbitMQ. The messages are still published, so no reason to worry.

For 2.0, the Publish Acknowledge is completely rewritten to better coop with the async operations. You can ignore the log entries, or - if it is annoying, you could turn Publish Acknowledgement off by following [the instructions in the documentation](http://rawrabbit.readthedocs.io/en/master/Publisher-Acknowledgements.html).

(Publish Acknowledgement is off by default in the underlying client, and disable it will increase throughput. However, RawRabbit has always sided on caution which is why it is activated by default there)

**Comment by PeterKottas** [comment]
Ok thanks for the info mate. Feel free to close this. Would do it myself but maybe you want to keep it open for now. No problem ignoring logs, was just curious.

**Comment by pardahlman** [comment]
Perfect - closing it for now!
