### ISSUE TITLE
Configuration not correctly bound when using ConfigurationBuilder

### ISSUE THREAD

**Issue by david-x-chen** [pardahlman/RawRabbit#216]
I follow the sample in branch 2.0 to try in ASP.NET core application project. It seems the settings I added in the appsettings.json is not useful.
I can see the output is correct while starting up. But in the controller, the connecting host is changed to localhost which I already changed to the remote server IP. Also the username and password have been reset to guest/guest which are not from the settings.

What's wrong? Did I do anything wrongly? 'Cause I followed the sample in branch 2.0. It should work, is it?

**Comment by pardahlman** [comment]
@david-x-chen, thanks for reporting this!

You are correct, something has changed in how configuration sections is bound to objects. When I debug the code, I see that it [binds the config to the object](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit.vNext/AddRawRabbitExtension.cs#L27-L35), but that binding does not give any effect.

If you are interested, you can play around with  `ConfigurationBuilder` and the `ConfigurationBinder` and you will probably find what's missing. In the mean while you can register the configuration through the `ClientConfiguration` section

```csharp
services
    .AddRawRabbit(new RawRabbitOptions
        {
            ClientConfiguration = new RawRabbitConfiguration
            {
                Username = "frodo"
            },
            DependencyInjection = ioc => ioc.AddSingleton(LoggingFactory.ApplicationLogger),
            Plugins = p => p
                .UseStateMachine()
                .UseGlobalExecutionId()
        })
```

Hope this helps!

**Comment by garethrampton** [comment]
The issue here is that the default constructor for RawRabbitConfiguration contains opinionated defaults. Specifically:
`			VirtualHost = "/";
			Username = "guest";
			Password = "guest";
			Port = 5672;
			Hostnames = new List<string> { "localhost" };`

These defaults should not be required because they are already present as the static:
`public static RawRabbitConfiguration Local => new RawRabbitConfiguration
		{
			VirtualHost = "/",
			Username = "guest",
			Password = "guest",
			Port = 5672,
			Hostnames = new List<string> { "localhost" }
		};`

The issue here though is that when the ASP.NET Core configuration system retrieves settings it **merges** these with a new'd instance of the target configuration object. So when accessing settings via something like:
`Configuration.GetSection("RabbitMQ").Get<RawRabbitConfiguration>();`
will result in your configured hostname(s) added to the existing list which always now includes "localhost".

I believe the most appropriate fix would be to remove the opinionated settings from the default RawRabbitConfiguration constructor.

**Comment by garethrampton** [comment]
FYI the change which causes this issue to the configuration class had been made in #159

**Comment by pardahlman** [comment]
Hi @garethrampton thanks for joining the conversation!

Looking through the git history, the change to the default constructor can be traced to this commit: https://github.com/pardahlman/RawRabbit/commit/1ccf7aa35e35c6e3542a862d2115d6815e0dff6e that is part of #159 just as you said. If I remember correctly, it was argued that it would be helpful with default values for new users trying out RawRabbit. It is, as you point out, perhaps not necessary, since you can always do `RawRabbitConfiguration.Local` to get the local defaults. @cemremengu what's you thoughts?

Looking a bit closer at the problem at hand, I removed the default values and new'd up a `RawRabbitConfiguration` object and bound it to the configuration, but none of the values from the json file ended up in the object. So I still suspect that there is something wrong with how we handle the Configuration Builder or perhaps Configuration Binder.

Any more suggestions?

**Comment by garethrampton** [comment]
So I think we've really got two related issues here:

1. When pulling configuration, ASP.NET Core merges the incoming settings with a new'd instance of the configuration object. Any incoming hostnames then get added to the default of "localhost". **Suggestion solution:** Remove the opinionated defaults as they're not required and frankly only useful for pure local development scenarios anyway.

2. The Configuration Builder does not correctly bind incoming configuration. This seems to happen regardless of whether pulling in configuration from the main appsettings or via a dedicated rawrabbit.json file. This obviously needs further investigation.

**Comment by pardahlman** [comment]
@garethrampton agree with you on both points! I think we should focus our fixes for the 2.0 branch, as there are no plans on releasing anything for 1.10.x ATM. Looking forward to see what you'll find!

**Comment by garethrampton** [comment]
So initial investigation confirms the current configuration builder approach simply doesn't work.

1. Passing in a configuration section (as per the sample app) as the Action<IConfigurationBuilder> simply won't work. The new'd configuration builder never has any sources configured, and a valid source cannot be created from a specific configuration section.

2. If passing the configuration builder action with a dedicated config file - for example via .AddJsonFile("rawrabbit.json") then you need to be sure to set the base path (or pass in a full file path) otherwise the new'd ConfigurationBuilder won't find the source. In this scenario the ConfigurationBuilder correctly picks up the source and does bind the configuration. However, we still see the issue where the list of hostnames is added to rather than replaced because the new'd RawRabbitConfiguration is set as RawRabbitConfiguration.Local which of course includes localhost. The merging of existing properties rather than replacing is I believe the desired behavior of the Core configuration system.

My suggestion for solving this is actually rather brute force - I'd be inclined to remove the Action<IConfigurationBuilder> Configuration entirely from RawRabbit.vNext.Pipe.RawRabbitOptions.

I also don't necessarily feel that the presence of Action<IConfigurationBuilder> Configuration enhances anything in the way of additional plug-ability, or ease of use. In fact I think it makes ease of use more complicated because I can specify both ClientConfiguration AND Configuration together - and it is not immediately obvious to the developer that the supplied Configuration will take preference over ClientConfiguration.
Why not just leave it up to the dev to manage supplying configuration directly into the ClientConfiguration property instead. This way you can chose to use any existing appsettings.json, or any other standard mechanism to resolve config.

Thoughts?

**Comment by pardahlman** [comment]
> In fact I think it makes ease of use more complicated because I can specify both ClientConfiguration AND Configuration together

I fully agree with you. I think it makes sense to remove `Action<IConfigurationBuilder>` from the options object.

At the same time, I think it is quite elegant to be able to to extract the client configuration from the `IConfigurationRoot` without too much effort. One way this can be done would be to add an extension method to the `IConfigurationRoot` that makes it possible to extract a `RawRabbitConfiguration` object from it

```csharp
services
    .AddRawRabbit(new RawRabbitOptions
    {
        ClientConfiguration = Configuration.GetRawRabbitConfig(),
    })
```

It could have an optional argument for section key that default to `RawRabbit`. What do you think, @garethrampton?

**Comment by garethrampton** [comment]
@pardahlman yes, I think this would work well. 

Whilst you could achieve the same using::
`services
    .AddRawRabbit(new RawRabbitOptions
    {
        ClientConfiguration = ((IConfiguration)Configuration.GetSection("RabbitMQ")).Get<RawRabbitConfiguration>(),
    })`
this would also mean taking a dependency on Microsoft.Extensions.Configuration.Binder in order to have access to the Get<> extension method on IConfiguration, so the GetRawRabbitConfig extension is probably simpler.

**Comment by pardahlman** [comment]
Thanks for your input. In fact, we already [have that dependency](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit.vNext/RawRabbit.vNext.csproj#L26), it's just to a lower version that doesn't have the `Get<T>` extension method.

The way I see it, we can go two different ways:

1. Remove all dependencies to `Microsoft.Extensions.Configuration` and have the developer extract the configuration however s/he wants to.
2. Upgrade the dependency for `Microsoft.Extensions.Configuration.Binder` and add the extension method we discussed above.

I can see compelling arguments for both approaches. Especially the first approach, as it will be (is?) an everyday task to bind configuration to a POCO and it will result in less code to maintain. At the other hand, it removes the friction in getting started with RawRabbit if there is a simple way to create the `RawRabbitConfiguration` from the configuration object.

Input? 🤔

**Comment by pardahlman** [comment]
So, I sided with the second approach.

1. Local config removed from `RawRabbitConfiguration` constructor
2. The `Action<IConfigurationBuilder>` removed from the vNext configuration object
3. An extension method added to `IConfiguration` to bind a section to RawRabit

```csharpservices
  .AddRawRabbit(new RawRabbitOptions
    {
      ClientConfiguration = Configuration.ForRawRabbit(),
      DependencyInjection = ioc => ioc.AddSingleton(LoggingFactory.ApplicationLogger),
      Plugins = p => p
        .UseStateMachine()
        .UseGlobalExecutionId()
    })
  .AddMvc();
```

**Comment by pardahlman** [comment]
@david-x-chen you should be able to use use the updated signatures in beta6!
