### ISSUE TITLE
SubscribeAsync queueName

### ISSUE THREAD

**Issue by Towmeykaw** [pardahlman/RawRabbit#225]
Hello. Im using 2.0-beta6 and have a question regarding queue names. I have three applications all subscribing to the same published message of type Request. But they all connect to the same queue in RabbitMQ with the name "request". Is this the intended behavior? I have fixed it for now by using a CustomNamingConvension which uses the SubscriberQueueSuffix from NamingConvension.

**Comment by pardahlman** [comment]
Top of the morning, @Towmeykaw ☕️ 

It is actually by design, and one thing that has changed from 1,x to 2.x. Previously, RawRabbit appended an "application name" suffix to each queue - this functionality is moved to a separate package, [`RawRabbit.Enrichers.QueueSuffix`](https://www.nuget.org/packages/RawRabbit.Enrichers.QueueSuffix/). You can read more in [the upcoming documentation](https://github.com/pardahlman/RawRabbit/blob/2.0/docs/enrichers/queue-name-suffix.md) (work in progress!).

From what you describe, it sounds like you want to use the `.UseHostQueueSuffix()` plugin.

Hope this helps!

**Comment by Towmeykaw** [comment]
Great! That was exactly what i needed.

**Comment by pardahlman** [comment]
Great!
