### ISSUE TITLE
Sample Configuration for "Work Queues" Pattern

### ISSUE THREAD

**Issue by honekadi** [pardahlman/RawRabbit#240]
Would it be possible to add an sample of setting up RawRabbit for "Work Queue" pattern. (see RabbitMQ tutorial)

**Comment by pardahlman** [comment]
Good evening, @honekadi!

Have you [read the documentation](http://rawrabbit.readthedocs.io/en/master/Multiple-Subscribers-for-Messages.html) for multiple subscribers? I think that you might find it that `RawRabbit` supports Worker Queue pattern out of the box for some scenarios.

There is also [a work queue unit test](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/RabbitMqTutorial/WorkQueueTest.cs#L24) that I wrote some time ago. If the tutorials haven't changed since then, you should have the exact same topology features there as in the tutorial.

Hope this helps 👋

**Comment by honekadi** [comment]
Hallo Pär,

thank you for the information – meanwhile the prototyp is running.

Best regards

Dirk

Von: Pär Dahlman <notifications@github.com>
Antworten an: pardahlman/RawRabbit <reply@reply.github.com>
Datum: Sonntag, 16. Juli 2017 um 17:16
An: pardahlman/RawRabbit <RawRabbit@noreply.github.com>
Cc: honekadi <dirk.honekamp@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [pardahlman/RawRabbit] Sample Configuration for "Work Queues" Pattern (#240)


Good evening, @honekadi<https://github.com/honekadi>!

Have you read the documentation<http://rawrabbit.readthedocs.io/en/master/Multiple-Subscribers-for-Messages.html> for multiple subscribers? I think that you might find it that RawRabbit supports Worker Queue pattern out of the box for some scenarios.

There is also a work queue unit test<https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/RabbitMqTutorial/WorkQueueTest.cs#L24> that I wrote some time ago. If the tutorials haven't changed since then, you should have the exact same topology features there as in the tutorial.

Hope this helps 👋

**Comment by pardahlman** [comment]
Glad to hear it!
