### ISSUE TITLE
Using the AddRawRabbit Extension should not overwrite registrations

### ISSUE THREAD

**Issue by JoeStead** [pardahlman/RawRabbit#241]
When using the `AddRawRabbit` ServiceCollection extension method, it currently overwrites any existing registrations.

Instead of overwriting existing registrations, it should only register the type if one does not already exist.

**Comment by pardahlman** [comment]
Top of the evening, @JoeStead 👋  Thanks for reporting this!

I have to make some assumptions, as it is not 100% clear to me what your setup is like.

* I'm assuming that you are running the 1.x version of the client
* I'm assuming that you are using the extension methods from `RawRabbit.vNext` (rather than the ones from `RawRabbit.Extensions`).
* I also assume that you are registering RawRabbit internal services by providing them as an argument to the extension, as [per the documentation](http://rawrabbit.readthedocs.io/en/master/configuration.html).

The [last thing that happens](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit.vNext/IServiceCollectionExtensions.cs#L115) before returning the `IServiceCollection` is that the `custom` delegate/action is called. This ensures that whatever custom configuration that is provided in the `AddRawRabbit` call is registered last.

Let me know if any of my assumptions are wrong and feel free to post a snippet of how you register RawRabbit and how I can reproduce it.

Take care!

**Comment by pardahlman** [comment]
Hello again, @JoeStead - I haven't heard from you in a while, so closing this issue for now. Feel free to re-open if you have any more input on the topic!
