### ISSUE TITLE
vNext & default ChannelFactory

### ISSUE THREAD

**Issue by timothybeutels** [pardahlman/RawRabbit#59]
The vNext IServiceCollection extension AddRawRabbit does not seem to setup RawRabbit correctly for use in a (ASP.NET 5) web-context.

1. it registers ChannelFactory as a singleton.
2. IBusClient<T> is registered as Transient with concrete type BaseBusClient.

Since the client is registered as transient it will be constructed and disposed of once per request for each service dependency of that request which has a dependency on IBusClient.

BaseBusClient<T> in turn diposes of it's ChannelFactory instance.

The ChannelFactory is however, in fact, never actually disposed and will be reused for subsequent activation of another IBusClient. Calling dipose on it does render the ChannelFactory useless for this purpose, as it disposes of it's _threadChannels.

I'm not sure what the intended behavior is here, but I'm guessing ChannelFactory should actually be used/registered as a singleton.

The use case for generating a new BusClient for each service requesting it makes sense, mostly in environments which are intended for message processing. (Maybe not so much in web-based environments where the BusClient might be used to push something on the queue.) However, as soon as the first BusClient is disposed of, all other existing instances will fall flat. (Issue 1?)

Actual issue:
BaseBusClient should not dispose of it's dependencies.
I think it would be safe to delegate this to the DI container? Ie. with the default configuration, they should never be disposed.

**Comment by timothybeutels** [comment]
Also, as a suggestion; Would it make sense to add a PublishingBusClient? 
This Client could be registered as a singleton and could be safely reused for publish-only environments.

I would be interested in contributing, if you are interested.

**Comment by pardahlman** [comment]
@timothybeutels - thanks for reporting!

You are correct that the disposal of one bus client will affect channels and connections for all the other instances, which is especially bad for web applications. The reason why the bus client disposes its dependencies is because the same `IServiceCollectionExtension` is used in the factory class `BusClientFactory` to create an instance where the service collection works as an "inner" ioc container. The factory method is typically used to create an instance of  `BusClient` and register it as singleton in the application IoC container. In this scenario, the inner and outer IoC containers are separated, and when disposing the bus client it needs to take care of disposing channels and connections.

However, I'm open for suggestions here. We should prime the `AddRawRabbit` extension for web application, but we need to have a solution for the factory method scenario as well. Any ideas?

**Comment by pardahlman** [comment]
Regarding a `PublishBusClient`, I'm not sure I understand when this should be needed? If we make sure that the IoC registration is correct (that is, make sure `IChannelFactory` and `IConnectionFactory` are non-disposed singeltons throughout the application life cycle), a normal `IBusClient` can be used as a publisher. The default implementation of `PublishAsync` reuses channels, is thread safe and performs well for multiple concurrent tasks. Can you explain when you should need a `PublishBusClient`?

**Comment by pardahlman** [comment]
Still feel like contributing? It is much appreciated! I haven't had time to write a contributor manual, but basically

1. Prefix commit with issue number like `(#59) Fix this and that`
2. Follow guide lines for commits http://chris.beams.io/posts/git-commit/
3. Pull-request to `stable`

Thanks -- looking forward hearing from you

**Comment by pardahlman** [comment]
@timothybeutels good news - this issue will be fixed in upcoming release `1.8.12`. All operations have been optimized for multiple concurrent calls. That way, the `BusClient` can be registered as a singelton and reused throughout the entire lifetime of the application.  Not quite the solution you where proposing, but I think it will do the trick.
